### ISSUE TITLE
 ProtoEntity对象print问题？

### ISSUE THREAD

**Issue by fordoo** [yihuang/cprotobuf#12]
ProtoEntity对象print问题：

    def __unicode__(self):
        buf = []
        d = self.__dict__
        for f in self._fields:
            value = d.get(f.name)
            if value == None:
                continue
            if f.repeated:
                buf.append(u'%s = [%s]' % (f.name, u','.join(map(unicode, value))))
            else:
                buf.append(u'%s = %s' % (f.name, unicode(value)))
        return u'\n'.join(buf)

当repeated和嵌套稍微多点的时候，因为没有对齐，输出很难找到'['对应的']'，输出例子：

	a = [
	b = [
	c = 1
	d = [
	e = 2
	]
	]
	f = 3
	]

输出看起来很费力，要不要考虑进行优化一下。

另外我暂时的解决办法是为ProtoEntity增加一个todict的方法：

    def todict(self):
        data = {}
        d = self.__dict__
        for f in self._fields:
            value = d.get(f.name)
            if value == None:
                continue
            if f.repeated:
                if len(value) < 1:
                    continue
                if isinstance(value[0], ProtoEntity):
                    data[f.name] = [v.todict() for v in value]
                else:
                    data[f.name] = value
            else:
                if isinstance(value, ProtoEntity):
                    data[f.name] = value.todict()
                else:
                    data[f.name] = value
        return data

**Comment by yihuang** [comment]
`todict` looks good, I've added it and changed `__str__` to use it.
