### ISSUE TITLE
Support memoryview/bytearray

### ISSUE THREAD

**Issue by Downchuck** [yihuang/cprotobuf#13]
I'm passing data from buffers as a memoryview, and I'd like to pass that data into cprotobuf directly.

Currently I must copy the data: pb.ParseFromString(bytes(bytearray(data)))

EDIT: This seems to work, though I'm not sure how rugged it is:
```
data.base.tobytes()
```

**Comment by yihuang** [comment]
-    def ParseFromString(self, bytes s):
+    def ParseFromString(self, s):
         cdef char *buff = <char*>s

Please test this modification, to check if it works with memoryview.

**Comment by Downchuck** [comment]
Looks like it supports bytearray:
```
pb.ParseFromString(bytearray(data))
```

That's an improvement. Given that a memoryview may be spread across several strides, I think this is as good as we can get for a direct cast.

I'm going to consider this fixed, as bytearray can now be used directly.

-Charles

**Comment by Downchuck** [comment]
I could use a ParseFromBuffer method which allows start/end parameters:
```
ParseFromBuffer(data.base, 0, len(data))
```

It seems that bytebuffer and memoryview are encouraged in many documents, though it does seem to be a lot of extra work.

**Comment by Downchuck** [comment]
This is what I'm thinking:
```
-    def ParseFromString(self, bytes s):
+    def ParseFromString(self, s, offset = 0, length = -1):
         cdef char *buff = <char*>s
         cdef char *start
         cdef char *end
         cdef Py_ssize_t size = len(s)
+
+        if offset > 0:
+                buff += offset
+                size -= offset
+        if length > 0 and length <= size:
+                size = length
+        if length > size or size < 0:
+                raise makeDecodeError(s, "Offsets provided were out of bounds.")
+
         start = buff
         end = buff + size
```

**Comment by Downchuck** [comment]
No luck on memoryview. Big set of utility here:
https://github.com/cython/cython/blob/master/Cython/Utility/MemoryView.pyx

**Comment by Downchuck** [comment]
Had to give up on supporting memoryview -- still needed offset/length to work with the underlying bytearray. That's an ok situation.

This did not work out:
```
        if isinstance(s, memoryview):
                buff = PyBytes_AsString(s)
```

**Comment by Downchuck** [comment]
@yihuang Are you ok with that patch I provided?

**Comment by yihuang** [comment]
How about sending a *real* pull request?

**Comment by yihuang** [comment]
Ok, I've pushed it, please test it for me.

**Comment by Downchuck** [comment]
Thank you @yihuang looks good.
