### ISSUE TITLE
ParseFromString runs a merge on arrays

### ISSUE THREAD

**Issue by Downchuck** [yihuang/cprotobuf#14]
Repeated calls to ParseFromString when repeated container is used will result in parsed items being appended to the list. This is the behavior that Google's reference MergeFromString has (I believe) -- but their ParseFromString runs Clear first, which clears those repeated containers.

**Comment by yihuang** [comment]
I don't think we need Clear api, although it would be incompatible with official implementation, because we can always create a new instance for a clean parse.
I'll add a note to this behavior.
