### ISSUE TITLE
Could not install cprotobuf==0.1.5

### ISSUE THREAD

**Issue by aramd** [yihuang/cprotobuf#19]
Could not find cprotobuf/internal.c file and really there is no internal.c in repository. 

> pip install cprotobuf==0.1.5

Collecting cprotobuf==0.1.5
  Using cached cprotobuf-0.1.5.tar.gz
Building wheels for collected packages: cprotobuf
  Running setup.py bdist_wheel for cprotobuf ... error
  Complete output from command /home/aram/rtb_1106/rtb_1106/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3cty_w/cprotobuf/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpgM26_Jpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/cprotobuf
  copying cprotobuf/__init__.py -> build/lib.linux-x86_64-2.7/cprotobuf
  copying cprotobuf/plugin_pb.py -> build/lib.linux-x86_64-2.7/cprotobuf
  running build_ext
  building 'cprotobuf.internal' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/cprotobuf
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c cprotobuf/internal.c -o build/temp.linux-x86_64-2.7/cprotobuf/internal.o
  x86_64-linux-gnu-gcc: error: cprotobuf/internal.c: No such file or directory
  x86_64-linux-gnu-gcc: fatal error: no input files
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for cprotobuf
  Running setup.py clean for cprotobuf
Failed to build cprotobuf
Installing collected packages: cprotobuf
  Running setup.py install for cprotobuf ... error
    Complete output from command /home/aram/rtb_1106/rtb_1106/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3cty_w/cprotobuf/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-jiMvgb-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/aram/rtb_1106/rtb_1106/include/site/python2.7/cprotobuf:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/cprotobuf
    copying cprotobuf/__init__.py -> build/lib.linux-x86_64-2.7/cprotobuf
    copying cprotobuf/plugin_pb.py -> build/lib.linux-x86_64-2.7/cprotobuf
    running build_ext
    building 'cprotobuf.internal' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/cprotobuf
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c cprotobuf/internal.c -o build/temp.linux-x86_64-2.7/cprotobuf/internal.o
    **x86_64-linux-gnu-gcc: error: cprotobuf/internal.c: No such file or directory
    x86_64-linux-gnu-gcc: fatal error: no input files**
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by yihuang** [comment]
You should have cython installed.

**Comment by aramd** [comment]
Thanks, it works
