### ISSUE TITLE
benchmark 中的问题

### ISSUE THREAD

**Issue by yoki123** [yihuang/cprotobuf#2]
应该加入先编译pb为模块，再使用protobuf的cpp接口的测试。
我直接改的bench_proto， 测试结果如下，decode更快

	root@ubuntu:/tmp/cprotobuf/benchmark# ./bench.sh 
	encode[google official pure python]:
	10 loops, best of 3: 69.4 msec per loop
	encode[google official cpp python]:
	100 loops, best of 3: 5.28 msec per loop
	encode[py-protobuf][cython]:
	100 loops, best of 3: 3.52 msec per loop
	decode[google official pure python]:
	10 loops, best of 3: 44 msec per loop
	decode[google official cpp python]:
	1000 loops, best of 3: 1.31 msec per loop
	decode[py-protobuf][cython]:
	1000 loops, best of 3: 1.95 msec per loop

decode速度比cprotobuf快点

另外官方的cpp接口，速度慢的主要原因是对象的初始化，  单独调用 ParseFromString/SerializeToString函数还是很快的（不含初始化的情况下，我的测试上述方法比cprotobuf的序列/反序列都是快5倍左右），当然程序中不可避免要初始化。

编译pb为模块参照的：http://yz.mit.edu/wp/fast-native-c-protocol-buffers-from-python/

最后，cprotobuf还是很不错的。
提供了字典直接序列化，这个非常很赞。

**Comment by yihuang** [comment]
恩，你说的这个方法确实没试过，不过看起来太繁琐了，尤其是协议文件多了以后，加一个协议还要修改setup.py。
Python对象构建确实是开销很大，字典序列化也是为了专门处理我们自己这里一个大协议包的性能问题。
如果解码是瓶颈的话，也可以考虑解成字典应该还会有提升。或者有些protobuf实现支持lazy decode，只解码需要的字段，只是我这边暂时没这些需求 ;D

**Comment by fordoo** [comment]
setup.py不是必需的，自己写个makefile文件也可以，只需要动态生成makefile即可。
创建对象开销的问题可以通过pypy解决，但是pypy的I/O处理着实挺着急的。
