### ISSUE TITLE
Can't install cprotobuf==0.1.11 Python 3.9.16

### ISSUE THREAD

**Issue by krik99** [yihuang/cprotobuf#23]
Hi, I can't install cprotobuf 0.1.11 package with Python 3.9.16. Cython currently has installed.
The error occurs only with version 0.1.11, older versions install without problems.
The problem is:
```
cythoning cprotobuf/internal.pyx to cprotobuf/internal.c
error: /tmp/pip-install-d7suv1o1/cprotobuf_09545fc7cde340b4bd88e8d7b6c5e169/cprotobuf/internal.pyx
```
I can collect more logs during installation if it helps, but tell me how to get them cause pip use subprocess for installation.
What could be the problem?

**Comment by yihuang** [comment]
have no idea, what `cython --version` do you use?

**Comment by krik99** [comment]
Cython version 0.29.34

**Comment by yihuang** [comment]
Are there more detailed error messages

**Comment by krik99** [comment]
I think I solved the problem. I was trying to install package from PyPI (like by default) and get the error. When I install from local files downloaded master branch - it's done successfully. So it looks like the problem on PyPl. Thanks for the help, sorry about bothering😅
