### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by masihyeganeh** [yihuang/cprotobuf#9]
Are you going to make it compatible with python 3?

Install log on Mac:
```
Collecting cprotobuf
  Using cached cprotobuf-0.1.4.tar.gz
Installing collected packages: cprotobuf
  Running setup.py install for cprotobuf
    Complete output from command /path/to/project/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/s6/vy6lsvy52t10dklqxlyvxx7w0000gn/T/pycharm-packaging0.tmp/cprotobuf/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/s6/vy6lsvy52t10dklqxlyvxx7w0000gn/T/pip-8h9upbrq-record/install-record.txt --single-version-externally-managed --compile --install-headers /path/to/project/bin/../include/site/python3.4/cprotobuf:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.10-x86_64-3.4
    creating build/lib.macosx-10.10-x86_64-3.4/cprotobuf
    copying cprotobuf/__init__.py -> build/lib.macosx-10.10-x86_64-3.4/cprotobuf
    copying cprotobuf/plugin_pb.py -> build/lib.macosx-10.10-x86_64-3.4/cprotobuf
    running build_ext
    cythoning cprotobuf/internal.pyx to cprotobuf/internal.c
    warning: cprotobuf/utils.pxi:8:4: bytearray already a builtin Cython type
    building 'cprotobuf.internal' extension
    creating build/temp.macosx-10.10-x86_64-3.4
    creating build/temp.macosx-10.10-x86_64-3.4/cprotobuf
    clang -Wno-unused-result -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/usr/local/opt/sqlite/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/include/python3.4m -c cprotobuf/internal.c -o build/temp.macosx-10.10-x86_64-3.4/cprotobuf/internal.o
    cprotobuf/internal.c:1837:18: error: no member named 'ob_size' in 'PyByteArrayObject'
      __pyx_v_array->ob_size = __pyx_v_size;
      ~~~~~~~~~~~~~  ^
    cprotobuf/internal.c:4289:18: error: no member named 'ob_size' in 'PyByteArrayObject'
      __pyx_v_array->ob_size = __pyx_v_ss;
      ~~~~~~~~~~~~~  ^
    cprotobuf/internal.c:4676:18: error: no member named 'ob_size' in 'PyByteArrayObject'
      __pyx_v_array->ob_size = (__pyx_v_buff - __pyx_v_array->ob_bytes);
      ~~~~~~~~~~~~~  ^
    cprotobuf/internal.c:9604:15: warning: implicit declaration of function 'PyString_AsStringAndSize' is invalid in C99 [-Wimplicit-function-declaration]
      __pyx_t_1 = PyString_AsStringAndSize(__pyx_v_s, (&__pyx_v_buff), (&__pyx_v_size)); if (unlikely(__pyx_t_1 == -1)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 248; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                  ^
    1 warning and 3 errors generated.
    error: command 'clang' failed with exit status 1
    
    ----------------------------------------

    Command "/path/to/project/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/s6/vy6lsvy52t10dklqxlyvxx7w0000gn/T/pycharm-packaging0.tmp/cprotobuf/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/s6/vy6lsvy52t10dklqxlyvxx7w0000gn/T/pip-8h9upbrq-record/install-record.txt --single-version-externally-managed --compile --install-headers /path/to/project/bin/../include/site/python3.4/cprotobuf" failed with error code 1 in /private/var/folders/s6/vy6lsvy52t10dklqxlyvxx7w0000gn/T/pycharm-packaging0.tmp/cprotobuf
```

**Comment by yihuang** [comment]
I'm working on it.

**Comment by yihuang** [comment]
It's done, it passes my tests, please let me known if it works for you.

**Comment by sbant** [comment]
I have install cprotobuf and try use protoc-gen-cprotobuf

in protoc-gen-cprotobuf line 7, python3 has no StringIO
it can change to "from io import StringIO" or use try .. except ..

after changed, I got these error:
D:\dd>D:\WinPython-64bit-3.4.3.3\python-3.4.3.amd64\python protoc-gen-cprotobuf
ts_ui.proto -d .
Traceback (most recent call last):
  File "cprotobuf\internal.pyx", line 252, in cprotobuf.internal.ProtoEntity.Par
seFromString (cprotobuf\internal.c:9447)
  File "cprotobuf\internal.pyx", line 326, in cprotobuf.internal.decode_object (
cprotobuf\internal.c:10763)
cprotobuf.internal.InternalDecodeError: (42412113, "Can't skip enough bytes for
wire_type 3 at [{0}] for value")

my environment is python 3.4-x64 windows

**Comment by yihuang** [comment]
Currently i don't have the time to test and fix python3 problems thoroughly, it would be great if you can submit a pull request.

**Comment by sbant** [comment]
sorry, I tried but I don't understand  protoc-gen-cprotobuf  line 135-155, especially the 'yield' and 'for' at same intend under  'if'

any way...
these changes should add

add ' from __future__ import print_function ' to the front of file

I'm not sure these need change: 
if sys.version_info.major == 2:
     # py2_code
else:
     # py3 code

' dict.items() -> list(dict.items())  '
for name, attr in index_by_name.items():   line 138
for k, v in deps.items():                               line 143
for name, attr in index_by_name.items():    line 153

python2 dict.items()  return a list, python3 retrun a view

**Comment by gromakovsky** [comment]
There are some bugs because of which it fails with python3.
1. In python3 `stdin.read()` returns `str` and `stdout.write()` takes `str`, that's why
> request.ParseFromString(stdin.read())

and

> stdout.write(response.SerializeToString())

fail.
2. Also there is loop over dict where you modify its content which doesn't work in python3 since `items()` returns view (as was already stated by sbant).

This diff solved these problems for me: http://sprunge.us/PJGj

P. S. Also it would be great if you bump version and pypi so that python3-compatible version is available via pypi.

**Comment by yihuang** [comment]
@gromakovsky Thanks for the patch, I've changed a little to keep it compatible with both py2 and py3, please check it out. 
I will upload to pypi ASAP if it not break anything.

**Comment by gromakovsky** [comment]
Good, thank you!
